name: TafoJazzFx
options:
  bundleIdPrefix: com.tafoya
  deploymentTarget:
    iOS: "15.0"

packages:
  AudioKit:
    url: https://github.com/AudioKit/AudioKit.git
    from: 5.6.0

targets:
  TafoJazzFX:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - TafoJazzFX
    dependencies:
      - package: AudioKit
        product: AudioKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tafoya.TafoJazzFx
        SWIFT_VERSION: 5.0
