name: TafoJazzFx
options:
  bundleIdPrefix: com.tafoya

packages:
  AudioKit:
    url: https://github.com/AudioKit/AudioKit.git
    from: 5.6.0

targets:
  TafoJazzFX:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - .
    dependencies:
      - package: AudioKit
        product: AudioKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tafoya.TafoJazzFx
        SWIFT_VERSION: 5.0

schemes:
  TafoJazzFx:
    build:
      targets:
        TafoJazzFX: all
